#!/usr/bin/env bash

echo "Qual pasta você está procurando?"
read "nomepasta"


if [[ -e "$nomepasta" ]]; then
    echo "A pasta EXISTE!"
    exit
else
    echo "A pasta NÃO existe!"
    echo "Deseja cria-la? (S)sim / (N)Não"
fi

read "resposta"

    if [[ "$resposta" = "S" ]]; then
      mkdir "$nomepasta"
       echo "Pasta criada com sucesso!"

elif [[ "$resposta" = "sim" ]]; then
      mkdir "$nomepasta"
       echo "Pasta criada com Sucesso!"

elif [[ "$resposta" = "Sim" ]]; then
      mkdir "$nomepasta"
       echo "Pasta criada com Sucesso!"

elif [[ "$resposta" = "SIM" ]]; then
      mkdir "$nomepasta"
       echo "Pasta criada com Sucesso!"

elif [[ "$resposta" = "s" ]]; then
      mkdir "$nomepasta"
       echo "Pasta criada com Sucesso!"

elif [[ "$resposta" = "N" ]]; then
   echo "A pasta não foi criada!"

elif [[ "$resposta" = "Nao" ]]; then
   echo "A pasta não foi criada!"

elif [[ "$resposta" = "Não" ]]; then
   echo "A pasta não foi criada!"

elif [[ "$resposta" = "nao" ]]; then
   echo "A pasta não foi criada!"

elif [[ "$resposta" = "n" ]]; then
   echo "A pasta não foi criada!"
fi
